[".local/.oh-my-tmux"]
type = "archive"
url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".local/share/fonts/Meslo"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip"
exact = true
